src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/choose-identity/choose-identity.component.scss
src/app/route-components/choose-identity/choose-identity.component.ts
src/app/utils-components/utils-components.module.ts

Text changes for BC Services Card

Changes to text in bcsc login page

---

api/apiAuth.js
src/app/route-components/verify-your-identity/verify-your-identity.component.ts
src/app/services/keycloak.service.ts

Refresh token changes

---

api/emailLayout.js
src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/choose-identity/choose-identity.component.ts
src/app/route-components/select-about/select-about.component.html
src/app/route-components/signin/signin.component.ts
src/app/route-components/verify-your-identity/verify-your-identity.component.html
src/app/services/data.service.ts
src/app/services/keycloak.service.ts

Changes to handle BC Services Card with no email address

Changes to handle BC Services Card with no email address

---

api/emailLayout.js
src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/choose-identity/choose-identity.component.scss
src/app/route-components/review-submit/review-submit.component.html
src/app/route-components/review-submit/review-submit.component.ts
src/app/route-components/verify-your-identity/verify-your-identity.component.html

Latest text changes

---

src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/contact-info-options/contact-info-options.component.html
src/app/route-components/contact-info-options/contact-info-options.component.ts
src/app/route-components/review-submit/review-submit.component.html

Fixing Terms Of Service text

---

src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/choose-identity/choose-identity.component.scss
src/app/route-components/contact-info-options/contact-info-options.component.html
src/app/route-components/select-about/select-about.component.html
src/app/route-components/verify-your-identity/verify-your-identity.component.html
src/app/utils-components/alert-success/alert-success.component.html
src/app/utils-components/alert-success/alert-success.component.scss

Text and label changes

---

src/app/app.component.ts
src/app/services/window-ref.service.spec.ts
src/app/services/window-ref.service.ts

Snowplow tracker added for every page

---

config/keycloak_realm_config.json
src/app/services/app-config.service.ts
src/index.html

Adding Keycloak Configuration

---

src/app/route-components/choose-identity/choose-identity.component.html
src/app/route-components/choose-identity/choose-identity.component.scss

IDIM wording changes

---

api/apiCustomFunctions.js
web/src/app/app-routing.module.ts
web/src/app/progress-bar/progress-bar.component.ts
web/src/app/route-components/payment/payment.component.html
web/src/app/route-components/payment/payment.component.scss
web/src/app/route-components/payment/payment.component.spec.ts
web/src/app/route-components/payment/payment.component.ts
web/src/app/route-components/review-submit/review-submit.component.ts
web/src/app/route-components/route-components.module.ts
web/src/app/services/data.json
web/src/app/services/data.service.ts
web/src/app/transom-api-client.service.ts

Changed the flow after the submission button in UI in order to integrate payment

FOI Web UI flow change after submission #673

---

api/apiDefinition.js
web/src/app/route-components/payment-complete/payment-complete.component.ts
web/src/app/route-components/review-submit-complete/review-submit-complete.component.ts
web/src/app/route-components/review-submit/review-submit.component.ts
web/src/app/services/data.service.ts
web/src/app/transom-api-client.service.ts

Remove captcha validation for submitting the request to email. This is done to prevent an error when the user takes too long to complete the payment exceeding the validity time of the captcha token.

Remove captcha validation for submitRequestEmail

---

api/apiCustomFunctions.js
api/emailLayout.js

Submit confirmation email to user for foi request submission

Confirmation email of payment and request submission#818

---

api/apiCustomFunctions.js
api/apiDefinition.js
api/foiRequestApiService.js
web/src/app/route-components/payment-complete/payment-complete.component.html
web/src/app/route-components/payment-complete/payment-complete.component.scss
web/src/app/route-components/payment-complete/payment-complete.component.ts
web/src/app/services/data.service.ts
web/src/app/transom-api-client.service.ts

Add methods, api calls, and UI components to handle sending receipt generation request

Integrate FOI web with cdogs api service from back-end

---

api/apiCustomFunctions.js
web/src/app/route-components/payment-complete/payment-complete.component.ts
web/src/app/transom-api-client.service.ts

Generate receipt and attach it to submission email

add receipt attachment to submission email

---

web/src/app/services/data.json

Fix Social Development and Poverty Reduction being its own public body as well

Fix public bodies ministries mapping

---

api/apiAuth.js
api/apiCaptcha.js
api/apiCustomFunctions.js

Fix apiCustomFunctions req.userDetails from req.authorisedDetails

---

web/src/app/route-components/payment-complete/payment-complete.component.html

Updated the textual description after stand up.

updated text desc. after payment success

---

api/apiCustomFunctions.js
web/src/app/route-components/payment-complete/payment-complete.component.html

Enabling back the CDOGS to try out something on DEV

Enabled CDOGS , tryout on DEV

---

web/package-lock.json

Reverts bcgov/foi-requests#258

Revert "Ticket 3221 (DEV) - bump xmlhttprequest + set-value"

---

web/package-lock.json

Reverts bcgov/foi-requests#257

Revert "Ticket 3221: (DEV) Bump url-parse + mixin-deep"

---

web/package-lock.json

Reverts bcgov/foi-requests#256

Revert "Ticket 3221 (DEV) - Bump socket io"

---

web/package-lock.json
web/package.json

Reverts bcgov/foi-requests#255

Revert "Ticket 3221 (DEV) - Bump tree kill + jsonschema"

---

web/package-lock.json
web/package.json

Reverts bcgov/foi-requests#264

Revert "Ticket 3221 (DEV) - Bump loader-utils and @angular-devkit/build-angular in /web"

---

web/package-lock.json

Reverts bcgov/foi-requests#268

Revert "Ticket 3221 (DEV) - Bump @babel/traverse"

---

web/package.json

Reverts bcgov/foi-requests#266

Revert "Ticket 3221 (DEV) - Bump loader-utils "

---

web/package-lock.json

Manual adjustment to package.lock.json to bump loader utils to 1.4.1

Ticket 3221 - Address Critical Vulnerability (loader-utils)

---

api/package-lock.json
api/package.json

Reverts bcgov/foi-requests#307

Revert "Ticket 3222 - API Dependabot Securitu Updates (High + Critical)"

---

api/package-lock.json

Reverts bcgov/foi-requests#331

Revert "Ticket 3237 - small change to pacakge lock for mkdir dependancy"

---

api/package-lock.json
api/package.json

Reverts bcgov/foi-requests#330 (Needed as Dependabot PR 306 causes dev to crash)

Revert "Ticket 3237 - HIGH Vunerability Fixes Part 2"

---

api/apiCaptcha.js
api/package.json
web/package.json

build issue on openshift

---

api/apiCaptcha.js
api/package.json
web/package.json

Reverts bcgov/foi-requests#355

Revert "build issue on openshift"

---

api/apiCaptcha.js
api/package-lock.json
api/package.json
web/package-lock.json

Rebuild package-lock to resolve build issue

Rebuild package-lock to resolve build issue

---

api/package-lock.json
web/package-lock.json

updated package-lock FOIMOD-3463

---

api/package-lock.json
api/package.json
web/package-lock.json
web/package.json

Resolving dependency conflicts

Resolving dependency conflicts

---

web/src/app/route-components/contact-info/contact-info.component.html
web/src/app/route-components/description-timeframe/description-timeframe.component.ts
web/src/app/route-components/general-info/general-info.component.html
web/src/app/route-components/getting-started2/getting-started2.component.html

2. fix general request cannot continue on description-timeframe

1. fix observation 1 & 2

---

api/emailLayout.js
web/package-lock.json
web/package.json
web/src/app/app.module.ts
web/src/app/route-components/contact-info-options/contact-info-options.component.html
web/src/app/route-components/contact-info-options/contact-info-options.component.ts
web/src/app/route-components/contact-info-options/delay-warning-dialog.component.ts
web/src/app/route-components/contact-info-options/delay-warning-dialog.html
web/src/app/route-components/contact-info-options/delay-warning-dialog.scss
web/src/app/route-components/description-timeframe/description-timeframe.component.ts

observation 1: make delay message a popup modal
observation 3: remove description

Fix Matt's observations FOIMOD-3463

---

web/src/app/route-components/child-information/child-information.component.html
web/src/app/route-components/contact-info/contact-info.component.html
web/src/app/route-components/contact-info/contact-info.component.ts
web/src/app/route-components/description-timeframe/description-timeframe.component.html
web/src/app/route-components/getting-started1/getting-started1.component.html
web/src/app/route-components/getting-started1/getting-started1.component.ts
web/src/app/route-components/ministry-confirmation/ministry-confirmation.component.ts
web/src/app/services/data.json

bug introduc

---

web/src/app/services/data.json

Reverts bcgov/foi-requests#414

Revert "updated JSON for bug release"

---

web/src/app/route-components/ministry-confirmation/ministry-confirmation.component.ts

Reverts bcgov/foi-requests#412

Revert "dollar erros"

---

web/src/app/route-components/description-timeframe/description-timeframe.component.html

fixed minor wording and punctuation

chore: fix minor wording

---

web/angular.json
web/package.json
web/tsconfig.json

Reverts bcgov/foi-requests#433

Revert "#FOIMOD-3801 KC package upgrade and other config changes"

---

web/src/app/route-components/childprotection-child/childprotection-child.component.html
web/src/app/route-components/childprotection-child/childprotection-child.component.scss
web/src/app/route-components/childprotection-parent/childprotection-parent.component.html
web/src/app/route-components/childprotection-parent/childprotection-parent.component.scss
web/src/app/route-components/youthincare-child/youthincare-child.component.html
web/src/app/route-components/youthincare-child/youthincare-child.component.scss
web/src/app/route-components/youthincare-parent/youthincare-parent.component.html
web/src/app/route-components/youthincare-parent/youthincare-parent.component.scss
web/src/app/services/data.json

This pull request introduces a tooltip feature across multiple components to display descriptions for suboptions, improving the user interface and providing additional context. It also updates the data source to include detailed descriptions for suboptions where applicable.

Ticket 3894: FOI REQUEST Form Updates (UX and UI updates to Tooltips)

---

api/index.js

FOI-3944: Generating new api image for ci/cd change

---

api/index.js

Reverts bcgov/foi-requests#452

Revert "FOI-3944: Generating new api image for ci/cd change"

---

.github/workflows/web-cd.dev.yml

Adding changes to manually trigger changes in the dev web deployment

FOI-3944: Trigger Web Deployment
